inputs:
- type: git
  branch: ${GIT_BRANCH}
  path: .tekton
  service: repo
- type: git
  branch: master
  service: ${TEKTON_CATALOG_REPO}
  path: container-registry
- type: git
  branch: master
  service: ${TEKTON_CATALOG_REPO}
  path: kubernetes-service
properties:
- name: git-repository
  value: ${GIT_REPO_URL} 
  type: text 
- name: git-branch
  value: ${GIT_BRANCH}
  type: text 
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: registry-region
  value: ${REGISTRY_REGION_ID}
  type: text
- name: registry-namespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: schematics-workspace-id
  value: ${SCHEMATICS_WORKSPACE_ID}
  type: text 
- name: image-name
  value: ${IMAGE_NAME}
  type: text 
- name: target-resource-group
  value: ${TARGET_RESOURCE_GROUP}
  type: text
- name: target-region
  value: ${TARGET_REGION_ID}
  type: text
triggers:
- eventListener: ManualListener
  name: ManualListener
  type: manual