version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - repo
toolchain:
  name: 'secure-file-storage-{{timestamp}}'
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'secure-file-storage'
      repo_url: $env.repository
      type: clone
      has_issues: false
      enable_traceability: false
  tekton-catalog:
    service_id: githubpublic
    parameters:
      repo_url: "https://github.com/open-toolchain/tekton-catalog"
      source_repo_url: "https://github.com/open-toolchain/tekton-catalog"
      type: "link"
      has_issues: false
      enable_traceability: false
      kind: ['pipeline']
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
        - tekton-catalog
      name: 'secure-file-storage ({{form.pipeline.parameters.branch-name}})'
      ui-pipeline: true
      type: $env.type
      configuration:
        content:
          $text: >
            $env.type + '.yml'
        env:
          GIT_REPO: repo
          GIT_REPO_URL: $env.repository
          GIT_BRANCH: '{{form.pipeline.parameters.branch-name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.target-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          IMAGE_NAME: '{{form.pipeline.parameters.image-name}}'
          TARGET_REGION_ID: '{{form.pipeline.parameters.target-region}}'
          SCHEMATICS_WORKSPACE_ID: '{{form.pipeline.parameters.schematics-workspace-id}}'
          TEKTON_CATALOG_REPO: tekton-catalog
        execute: true
form:
  pipeline:
    parameters:
      image-name: 'secure-file-storage'
      branch-name: $env.branch || 'master'
    schema:
      $ref: deploy.json
