apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: BUILD
spec:
  triggers:
  - binding:
      name: pipeline-BUILD
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-BUILD
spec:
  params:
  - name: script
    value: ./scripts/pipeline-BUILD.sh

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: DEPLOY
spec:
  triggers:
  - binding:
      name: pipeline-DEPLOY
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-DEPLOY
spec:
  params:
  - name: script
    value: ./scripts/pipeline-DEPLOY.sh

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ROTATE_STORAGE_CREDENTIALS
spec:
  triggers:
  - binding:
      name: pipeline-ROTATE-STORAGE-CREDENTIALS
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-ROTATE-STORAGE-CREDENTIALS
spec:
  params:
  - name: script
    value: ./scripts/pipeline-ROTATE_STORAGE_CREDENTIALS.sh

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ROTATE_APPID_CREDENTIALS
spec:
  triggers:
  - binding:
      name: pipeline-ROTATE-APPID-CREDENTIALS
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-ROTATE-APPID-CREDENTIALS
spec:
  params:
  - name: script
    value: ./scripts/pipeline-ROTATE_APPID_CREDENTIALS.sh

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ROTATE_REGISTRY_CREDENTIALS
spec:
  triggers:
  - binding:
      name: pipeline-ROTATE-REGISTRY-CREDENTIALS
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-ROTATE-REGISTRY-CREDENTIALS
spec:
  params:
  - name: script
    value: ./scripts/pipeline-ROTATE_REGISTRY_CREDENTIALS.sh

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: UNINSTALL
spec:
  triggers:
  - binding:
      name: pipeline-UNINSTALL
    template:
      name: tt-common
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-UNINSTALL
spec:
  params:
  - name: script
    value: ./scripts/pipeline-UNINSTALL.sh
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tt-common
spec:
  params:
  - name: GIT_REPO
  - name: GIT_BRANCH
  - name: REGISTRY_REGION_ID
  - name: REGISTRY_NAMESPACE
  - name: TARGET_CLUSTER_NAME
  - name: IMAGE_NAME
  - name: TARGET_REGION_ID
  - name: TARGET_NAMESPACE
  - name: TARGET_RESOURCE_GROUP
  - name: COS_PLAN
  - name: APP_ID_PLAN
  - name: CLOUDANT_PLAN
  - name: script
  resourcetemplates:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cd-secret
    type: Opaque
    stringData:
      API_KEY: $(params.API_KEY)
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pipelinerun-$(uid)-pvc
    spec:
      resources:
        requests:
          storage:  1Gi
      volumeMode: Filesystem
      accessModes:
      - ReadWriteOnce
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: pipeline-input-parameter-variable
      workspaces:
      - name: pipeline-workspace
        emptyDir: {}
        #persistentVolumeClaim:
        #  claimName: pipelinerun-$(uid)-pvc
      params:
      - name: GIT_REPO
        value: $(params.GIT_REPO)
      - name: GIT_BRANCH
        value: $(params.GIT_BRANCH)
      - name: REGISTRY_REGION_ID
        value: $(params.REGISTRY_REGION_ID)
      - name: REGISTRY_NAMESPACE
        value: $(params.REGISTRY_NAMESPACE)
      - name: TARGET_CLUSTER_NAME
        value: $(params.TARGET_CLUSTER_NAME)
      - name: IMAGE_NAME
        value: $(params.IMAGE_NAME)
      - name: TARGET_REGION_ID
        value: $(params.TARGET_REGION_ID)
      - name: TARGET_NAMESPACE
        value: $(params.TARGET_NAMESPACE)
      - name: TARGET_RESOURCE_GROUP
        value: $(params.TARGET_RESOURCE_GROUP)
      - name: COS_PLAN
        value: $(params.COS_PLAN)
      - name: APP_ID_PLAN
        value: $(params.APP_ID_PLAN)
      - name: CLOUDANT_PLAN
        value: $(params.CLOUDANT_PLAN)
      - name: script
        value: $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-input-parameter-variable
spec:
  workspaces:
  - name: pipeline-workspace
  params:
  - name: GIT_REPO
  - name: GIT_BRANCH
  - name: REGISTRY_REGION_ID
  - name: REGISTRY_NAMESPACE
  - name: TARGET_CLUSTER_NAME
  - name: IMAGE_NAME
  - name: TARGET_REGION_ID
  - name: TARGET_NAMESPACE
  - name: TARGET_RESOURCE_GROUP
  - name: COS_PLAN
  - name: APP_ID_PLAN
  - name: CLOUDANT_PLAN
  - name: script
  tasks:
  - name: script
    workspaces:
    - name: task-workspace
      workspace: pipeline-workspace
    params:
    - name: GIT_REPO
      value: $(params.GIT_REPO)
    - name: GIT_BRANCH
      value: $(params.GIT_BRANCH)
    - name: REGISTRY_REGION_ID
      value: $(params.REGISTRY_REGION_ID)
    - name: REGISTRY_NAMESPACE
      value: $(params.REGISTRY_NAMESPACE)
    - name: TARGET_CLUSTER_NAME
      value: $(params.TARGET_CLUSTER_NAME)
    - name: IMAGE_NAME
      value: $(params.IMAGE_NAME)
    - name: TARGET_REGION_ID
      value: $(params.TARGET_REGION_ID)
    - name: TARGET_NAMESPACE
      value: $(params.TARGET_NAMESPACE)
    - name: TARGET_RESOURCE_GROUP
      value: $(params.TARGET_RESOURCE_GROUP)
    - name: COS_PLAN
      value: $(params.COS_PLAN)
    - name: APP_ID_PLAN
      value: $(params.APP_ID_PLAN)
    - name: CLOUDANT_PLAN
      value: $(params.CLOUDANT_PLAN)
    - name: script
      value: $(params.script)
    taskRef:
      name: gasket
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gasket
spec:
  workspaces:
  - name: task-workspace 
    mountPath: /working   
  params:
  - name: GIT_REPO
  - name: GIT_BRANCH
  - name: REGISTRY_REGION_ID
  - name: REGISTRY_NAMESPACE
  - name: TARGET_CLUSTER_NAME
  - name: IMAGE_NAME
  - name: TARGET_REGION_ID
  - name: TARGET_NAMESPACE
  - name: TARGET_RESOURCE_GROUP
  - name: COS_PLAN
  - name: APP_ID_PLAN
  - name: CLOUDANT_PLAN
  - name: script
  steps:
  - name: echoenvvar
    image: ibmcom/pipeline-base-image
    envFrom:
    - configMapRef:
        name: environment-properties
    - secretRef:
        name: secure-properties     
    #env:
    #- name: API_KEY
    #  valueFrom:
    #    secretKeyRef:
    #      name: cd-secret
    #      key: API_KEY
    #- name: GIT_REPO
    #  value: $(params.GIT_REPO)
    #- name: GIT_BRANCH
    #  value: $(params.GIT_BRANCH)
    #- name: REGISTRY_REGION_ID
    #  value: $(params.REGISTRY_REGION_ID)
    #- name: REGISTRY_NAMESPACE
    #  value: $(params.REGISTRY_NAMESPACE)
    #- name: TARGET_CLUSTER_NAME
    #  value: $(params.TARGET_CLUSTER_NAME)
    #- name: IMAGE_NAME
    #  value: $(params.IMAGE_NAME)
    #- name: TARGET_REGION_ID
    #  value: $(params.TARGET_REGION_ID)
    #- name: TARGET_NAMESPACE
    #  value: $(params.TARGET_NAMESPACE)
    #- name: TARGET_RESOURCE_GROUP
    #  value: $(params.TARGET_RESOURCE_GROUP)
    #- name: COS_PLAN
    #  value: $(params.COS_PLAN)
    #- name: APP_ID_PLAN
    #  value: $(params.APP_ID_PLAN)
    #- name: CLOUDANT_PLAN
    #  value: $(params.CLOUDANT_PLAN)
    #- name: script
    #  value: $(params.script)
    command: ["/bin/bash", "-c"]
    args:
    - |
      env | sort
      exit 1
      cd /working

      # Builder type: Container Registry, initializes this default
      export ARCHIVE_DIR=.

      # Builder type: Kubernetes expects the ibmcloud cli to be connected to the cluster and the
      # environment exported below.  The ibmcloud cli region could be initialized to the toolchain
      # region instead of the kubernets cluster region
      export PIPELINE_KUBERNETES_CLUSTER_NAME="$TARGET_CLUSTER_NAME"
      ibmcloud config --check-version false
      ibmcloud login -r $TARGET_REGION_ID -g $TARGET_RESOURCE_GROUP --apikey $API_KEY
      ibmcloud ks cluster config --cluster $TARGET_CLUSTER_NAME
      # REGISTRY_URL is based on TARGET_REGION_ID, parse the output of the cr api command, the echo
      # removes the new lines expect: s="Registry API endpoint https://us.icr.io/api OK"
      r='.*https://([^/]*)'
      ibmcloud cr api; # just to see
      s=$(echo $(ibmcloud cr api))
      [[ $s =~ $r ]]
      export REGISTRY_URL=${BASH_REMATCH[1]}
      if [ -z $GIT_BRANCH ]; then
        git clone -q $GIT_REPO .
      else
        git clone -q -b $GIT_BRANCH $GIT_REPO .
      fi
      ./$script

    volumeMounts:
    - mountPath: /cd-config
      name: cd-config-volume
  volumes:
  - name: cd-config-volume
    configMap:
      name: toolchain
      items:
      - key: toolchain.json
        path: toolchain.json
